<?php
return [

    [
        'user_id' => 3,
        'title' => 'Alloggio-Host: Pirmin',
        'slug' => 'alloggio-host-pirmin',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Largo Ciro Menotti, 18, Pisa',
        'latitude' => 43.7176673,
        'longitude' => 10.4025949,
        'img' => 'image1.jpg',
        'price' => 1500.00,
        'description' => 'Ti diamo il benvenuto al nostro barile da campeggio numero 3 per un massimo di 3 persone su un meraviglioso altopiano sopra Küssnacht sul Rigi. La vista sul Lago dei Quattro Cantoni, sul Pilatus, fino al Rigi o agli amabili alpaca è meravigliosa. Intorno ci sono altri due barili da campeggio e una tenda LotusBelle bianca. La situazione ha tutto ciò che contraddistingue la Svizzera. Semplicemente natura pura curata nei dettagli. Una permanenza ti rimarrà sicuramente un ricordo meraviglioso.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Intero alloggio: chalet-Host: Manu',
        'slug' => 'intero-alloggio-chalet-host-manu',
        'n_rooms' => 2,
        'n_beds' => 2,
        'n_bathrooms' => 1,
        'mq' => 80,
        'address' => 'Via Merulana, 105, Roma',
        'latitude' => 41.8951042,
        'longitude' => 12.5001849,
        'img' => 'image2.jpg',
        'price' => 1200.00,
        'description' => 'Il nostro chalet si trova nel villaggio di La Crettaz d\'Eison a 1650 m di altitudine. Ci abbiamo vissuto per 5 anni. Oggi è diventato troppo piccolo per noi e abbiamo deciso di metterlo in affitto. Dall\'alloggio sono possibili diverse passeggiate (a piedi o con le racchette da neve, a seconda della stagione), in direzione del villaggio di Eison, della foresta o verso gli alpeggi. Saremo lieti di consigliarvi alcuni itinerari in base alle vostre esigenze.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Intero alloggio: casa-Host: Luca',
        'slug' => 'intero-alloggio-casa-host-Luca',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 2,
        'mq' => 90,
        'address' => 'Via Del Borghetto, 44, Pisa',
        'latitude' => 43.7122008,
        'longitude' => 10.4108351,
        'img' => 'image3.jpg',
        'price' => 1800.00,
        'description' => 'Un’oasi di pace, privacy e relax nella natura a pochi minuti dalle spiagge e dai più famosi luoghi della Costa Smeralda. Soffitti in legno con travi a vista, pavimenti in cotto, arredi dalle calde tonalità della terra e viste sulla campagna rendono la Villa Turchese un luogo sereno dove vorrete fermarvi. La piscina panoramica è circondata da un ampio giardino con ulivi e alberi da frutta.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Intero alloggio: chalet-Host: Florence',
        'slug' => 'intero-alloggio-chalet-host-florence',
        'n_rooms' => 4,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 160,
        'address' => 'Via Di Sant\' Erasmo, Roma',
        'latitude' => 41.884436,
        'longitude' => 12.500058,
        'img' => 'image4.jpg',
        'price' => 900.00,
        'description' => 'Questo piccolo chalet accogliente si trova a Les Bois, di fronte al Monte Bianco. A 5 minuti di auto dal centro della città e a 5 minuti a piedi fermate di autobus e treni. Il villaggio è situato in posizione ideale, tra Chamonix e Argentière. Il posto è tranquillo, senza essere lontano da tutto. Le partenze escursionistiche, le piste per lo sci di fondo, il golf, gli impianti di risalita sono facilmente raggiungibili.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Agriturismo-Host: Irene',
        'slug' => 'agriturismo-host-irene',
        'n_rooms' => 4,
        'n_beds' => 5,
        'n_bathrooms' => 4,
        'mq' => 20,
        'address' => 'Via San\' Giovanni in Laterano, 28, Roma',
        'latitude' => 41.888384,
        'longitude' => 12.4998437,
        'img' => 'image5.jpg',
        'price' => 2500.00,
        'description' => 'Monolocale di 20 mq con affaccio diretto  alla piscina e giardino, composto da un letto matrimoniale ( oppure 2 letti singoli), un bagno, angolo cottura e patio esterno.  l\'appartamento fa parte dell\' Agriturismo Fulet in cui sono presenti altri 4 appartamenti posti al primo piano dell\'edificio.( vedi foto). Parcheggio privato ed uso wifi gratuito.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Accogliente appartamento vicino al centro',
        'slug' => 'accogliente-appartamento-vicino-al-centro',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Via Roma, 123, Città 1',
        'latitude' => 41.12345,
        'longitude' => 12.34567,
        'img' => 'image1.jpg',
        'price' => 1500.00,
        'description' => 'Questo appartamento spazioso e luminoso si trova in una posizione ideale, a pochi passi dal centro città. Dispone di 3 camere da letto, 2 bagni e una cucina completamente attrezzata. Ideale per una famiglia o un gruppo di amici in cerca di comfort e convenienza.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Villa panoramica con piscina',
        'slug' => 'villa-panoramica-con-piscina',
        'n_rooms' => 5,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 300,
        'address' => 'Via delle Palme, 456, Città 2',
        'latitude' => 41.23456,
        'longitude' => 12.45678,
        'img' => 'image2.jpg',
        'price' => 2500.00,
        'description' => 'Questa lussuosa villa offre una vista panoramica mozzafiato sul mare e dispone di una piscina privata. Con 5 camere da letto, 3 bagni e un ampio giardino, è il luogo perfetto per una vacanza di lusso.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Loft moderno nel cuore della città',
        'slug' => 'loft-moderno-nel-cuore-della-citta',
        'n_rooms' => 1,
        'n_beds' => 2,
        'n_bathrooms' => 1,
        'mq' => 70,
        'address' => 'Via delle Stelle, 789, Città 3',
        'latitude' => 41.34567,
        'longitude' => 12.56789,
        'img' => 'image3.jpg',
        'price' => 1200.00,
        'description' => 'Questo moderno loft nel cuore della città offre un ambiente elegante e confortevole per i viaggiatori. Con una camera da letto, un bagno e una cucina open-space, è ideale per coppie in cerca di un soggiorno romantico.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento con vista sulla montagna',
        'slug' => 'appartamento-con-vista-sulla-montagna',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 2,
        'mq' => 100,
        'address' => 'Via dei Pini, 101, Città 4',
        'latitude' => 41.67890,
        'longitude' => 12.78901,
        'img' => 'image4.jpg',
        'price' => 1800.00,
        'description' => 'Questo appartamento offre una vista panoramica sulla montagna ed è situato in una zona tranquilla. Dispone di 2 camere da letto, 2 bagni e un ampio balcone dove potrete godervi il panorama.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Casa vacanza sulla spiaggia',
        'slug' => 'casa-vacanza-sulla-spiaggia',
        'n_rooms' => 4,
        'n_beds' => 5,
        'n_bathrooms' => 3,
        'mq' => 150,
        'address' => 'Via del Mare, 567, Città 5',
        'latitude' => 41.89012,
        'longitude' => 12.89012,
        'img' => 'image5.jpg',
        'price' => 2000.00,
        'description' => 'Questa casa vacanza si trova direttamente sulla spiaggia e offre un accesso diretto al mare. Con 4 camere da letto, 3 bagni e un ampio patio, è perfetta per una vacanza al mare in famiglia.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Chalet in montagna con vista panoramica',
        'slug' => 'chalet-in-montagna-con-vista-panoramica',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Via della Montagna, 789, Città 6',
        'latitude' => 41.34567,
        'longitude' => 12.56789,
        'img' => 'image6.jpg',
        'price' => 1600.00,
        'description' => 'Questo chalet si trova in una posizione panoramica in montagna e offre una vista spettacolare sulla valle. Con 3 camere da letto, 2 bagni e un ampio soggiorno con camino, è perfetto per una vacanza rilassante in montagna.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento moderno nel centro storico',
        'slug' => 'appartamento-moderno-nel-centro-storico',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 1,
        'mq' => 90,
        'address' => 'Via del Centro, 101, Città 7',
        'latitude' => 41.67890,
        'longitude' => 12.78901,
        'img' => 'image7.jpg',
        'price' => 1400.00,
        'description' => 'Questo appartamento moderno si trova nel cuore del centro storico e offre un design elegante. Dispone di 2 camere da letto, 1 bagno e una cucina completamente attrezzata.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Villa con piscina e giardino lussureggiante',
        'slug' => 'villa-con-piscina-e-giardino-lussureggiante',
        'n_rooms' => 4,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 200,
        'address' => 'Via delle Ville, 123, Città 8',
        'latitude' => 41.89012,
        'longitude' => 12.89012,
        'img' => 'image8.jpg',
        'price' => 2800.00,
        'description' => 'Questa villa di lusso offre una piscina privata e un ampio giardino lussureggiante. Con 4 camere da letto, 3 bagni e una cucina gourmet, è il luogo perfetto per una vacanza di lusso.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Appartamento panoramico con terrazza',
        'slug' => 'appartamento-panoramico-con-terrazza',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 110,
        'address' => 'Via del Panorama, 456, Città 9',
        'latitude' => 41.12345,
        'longitude' => 12.34567,
        'img' => 'image9.jpg',
        'price' => 1700.00,
        'description' => 'Questo appartamento offre una vista panoramica mozzafiato sulla città e dispone di una terrazza spaziosa. Con 3 camere da letto, 2 bagni e una cucina moderna, è ideale per una vacanza con vista.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Chalet in montagna con sauna e vasca idromassaggio',
        'slug' => 'chalet-in-montagna-con-sauna-e-vasca-idromassaggio',
        'n_rooms' => 4,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 150,
        'address' => 'Via della Relax, 101, Città 10',
        'latitude' => 41.23456,
        'longitude' => 12.45678,
        'img' => 'image10.jpg',
        'price' => 2200.00,
        'description' => 'Questo chalet in montagna offre una sauna privata e una vasca idromassaggio all\'aperto. Con 4 camere da letto, 3 bagni e una zona relax, è perfetto per una vacanza di benessere.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento accogliente con vista sul fiume',
        'slug' => 'appartamento-accogliente-con-vista-sul-fiume',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 1,
        'mq' => 80,
        'address' => 'Via del Fiume, 34, Città 11',
        'latitude' => 41.34567,
        'longitude' => 12.56789,
        'img' => 'image11.jpg',
        'price' => 1100.00,
        'description' => 'Questo appartamento accogliente offre una vista pittoresca sul fiume e una posizione tranquilla. Dispone di 2 camere da letto, 1 bagno e un soggiorno con balcone.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Villetta con giardino e barbecue',
        'slug' => 'villetta-con-giardino-e-barbecue',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 100,
        'address' => 'Via dei Giardini, 56, Città 12',
        'latitude' => 41.67890,
        'longitude' => 12.78901,
        'img' => 'image12.jpg',
        'price' => 1400.00,
        'description' => 'Questa villetta offre un ampio giardino con zona barbecue ideale per grigliate all\'aperto. Con 3 camere da letto, 2 bagni e una cucina completamente attrezzata, è perfetta per una vacanza in famiglia.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento con terrazza panoramica',
        'slug' => 'appartamento-con-terrazza-panoramica',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 1,
        'mq' => 70,
        'address' => 'Via della Terrazza, 78, Città 13',
        'latitude' => 41.89012,
        'longitude' => 12.89012,
        'img' => 'image13.jpg',
        'price' => 950.00,
        'description' => 'Questo appartamento dispone di una terrazza panoramica con vista sulla città. Con 2 camere da letto, 1 bagno e una cucina moderna, è ideale per una coppia in cerca di una vista mozzafiato.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Casa vacanza con piscina privata',
        'slug' => 'casa-vacanza-con-piscina-privata',
        'n_rooms' => 4,
        'n_beds' => 5,
        'n_bathrooms' => 3,
        'mq' => 150,
        'address' => 'Via della Piscina, 45, Città 14',
        'latitude' => 41.12345,
        'longitude' => 12.34567,
        'img' => 'image14.jpg',
        'price' => 2100.00,
        'description' => 'Questa casa vacanza offre una piscina privata e un ampio giardino con zona relax. Con 4 camere da letto, 3 bagni e una cucina completamente attrezzata, è perfetta per una vacanza di relax.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Chalet in montagna con vista sul lago',
        'slug' => 'chalet-in-montagna-con-vista-sul-lago',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Via del Lago, 67, Città 15',
        'latitude' => 41.23456,
        'longitude' => 12.45678,
        'img' => 'image15.jpg',
        'price' => 1800.00,
        'description' => 'Questo chalet in montagna offre una vista spettacolare sul lago e dispone di 3 camere da letto, 2 bagni e un soggiorno con camino. Ideale per gli amanti della natura.',
        'visible' => true,
    ],
];